### ISSUE TITLE
X axis with Date labels - limit on time covered by the axis?

### ISSUE THREAD

**Issue by AndyEm-BT** [dima117/Chart.AltLineChart#2]
The scatter chart is just what I have been looking for. I need to plot historical data dating back over a year (but only one data point per week). Initial tests worked fine, but I encountered something unexpected.

When plotting a chart with a Date/Time axis, as I increase the date range past a boundary, the chart simply doesn't display. It has worked fine with a small sample, so I increased the sample size until it stops displaying the chart. The boundary seems to be when the axis spans more than around 16 weeks. When I added day-by-day data, it broke after 113 days (16 weeks and 1 day).

FYI - I didn't have any problems plotting over 180 points over a couple of days (data every 15 minutes).

Browser: Chrome 42.0.2311.90

HTML code:

```
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    <!--<script src="ChartJS_library.js"></script>-->
    <script src="ChartJS.Core.min.js"></script>
    <script src="ChartJS.Scatter.min.js"></script>
</head>
<body>
  Testing ChartJS plotter
  <br>Drawing Canvas
    <canvas id="header-canvas2" width="640" height="480"></canvas>
  <br>Adding script to populate the charts
    <script>
        var ctx2 = document.getElementById("header-canvas2").getContext("2d");
    var ChartData2 = [
    {
      data: [
         { x: new Date('2013-10-20'), y: 681.80 }
        ,{ x: new Date('2013-10-27'), y: 682.08 }
        ,{ x: new Date('2013-11-03'), y: 682.49 }
        ,{ x: new Date('2013-11-10'), y: 682.86 }
        ,{ x: new Date('2013-11-17'), y: 683.49 }
        ,{ x: new Date('2013-11-24'), y: 664.06 }
        ,{ x: new Date('2013-12-01'), y: 664.31 }
        ,{ x: new Date('2013-12-08'), y: 664.87 }
        ,{ x: new Date('2013-12-15'), y: 665.06 }
        ,{ x: new Date('2013-12-22'), y: 665.43 }
        ,{ x: new Date('2013-12-29'), y: 665.68 }
        ,{ x: new Date('2014-01-05'), y: 666.50 }
        ,{ x: new Date('2014-01-12'), y: 667.81 }
        ,{ x: new Date('2014-01-19'), y: 677.43 }
        ,{ x: new Date('2014-01-26'), y: 677.84 }
        ,{ x: new Date('2014-02-02'), y: 684.07 }
        ,{ x: new Date('2014-02-09'), y: 684.64 }
/* Including any of the data below causes the chart to remain blank
        ,{ x: new Date('2014-02-16'), y: 690.58 }
        ,{ x: new Date('2014-02-23'), y: 691.21 }
        ,{ x: new Date('2014-03-02'), y: 691.30 }
        ,{ x: new Date('2014-03-09'), y: 699.11 }
        ,{ x: new Date('2014-03-16'), y: 701.06 }
        ,{ x: new Date('2014-03-23'), y: 702.64 }
        ,{ x: new Date('2014-03-30'), y: 706.17 }
        ,{ x: new Date('2014-04-06'), y: 717.31 }
        ,{ x: new Date('2014-04-13'), y: 718.21 }
        ,{ x: new Date('2014-04-20'), y: 720.10 }
        ,{ x: new Date('2014-04-27'), y: 720.18 }
        ,{ x: new Date('2014-05-04'), y: 731.09 }
        ,{ x: new Date('2014-05-11'), y: 734.92 }
        ,{ x: new Date('2014-05-18'), y: 746.10 }
        ,{ x: new Date('2014-05-25'), y: 749.14 }
        ,{ x: new Date('2014-06-01'), y: 749.37 }
        ,{ x: new Date('2014-06-08'), y: 749.78 }
        ,{ x: new Date('2014-06-15'), y: 749.89 }
        ,{ x: new Date('2014-06-22'), y: 750.00 }
        ,{ x: new Date('2014-06-29'), y: 750.16 }
        ,{ x: new Date('2014-07-06'), y: 750.25 }
        ,{ x: new Date('2014-07-13'), y: 760.00 }
        ,{ x: new Date('2014-07-20'), y: 760.01 }
        ,{ x: new Date('2014-07-27'), y: 760.10 }
        ,{ x: new Date('2014-08-03'), y: 760.15 }
        ,{ x: new Date('2014-08-10'), y: 766.05 }
        ,{ x: new Date('2014-08-17'), y: 766.19 }
        ,{ x: new Date('2014-08-24'), y: 766.31 }
        ,{ x: new Date('2014-08-31'), y: 769.44 }
        ,{ x: new Date('2014-09-07'), y: 779.02 }
        ,{ x: new Date('2014-09-14'), y: 787.34 }
        ,{ x: new Date('2014-09-21'), y: 790.15 }
        ,{ x: new Date('2014-09-28'), y: 790.16 }
        ,{ x: new Date('2014-10-05'), y: 790.29 }
        ,{ x: new Date('2014-10-12'), y: 790.35 }
        ,{ x: new Date('2014-10-19'), y: 790.98 }
        ,{ x: new Date('2014-10-26'), y: 791.04 }
        ,{ x: new Date('2014-11-02'), y: 791.36 }
        ,{ x: new Date('2014-11-09'), y: 803.86 }
        ,{ x: new Date('2014-11-16'), y: 804.42 }
        ,{ x: new Date('2014-11-23'), y: 804.54 }
        ,{ x: new Date('2014-11-30'), y: 823.62 }
        ,{ x: new Date('2014-12-07'), y: 855.37 }
        ,{ x: new Date('2014-12-14'), y: 855.51 }
        ,{ x: new Date('2014-12-21'), y: 863.94 }
        ,{ x: new Date('2014-12-28'), y: 864.01 }
        ,{ x: new Date('2015-01-04'), y: 864.01 }
        ,{ x: new Date('2015-01-11'), y: 874.45 }
        ,{ x: new Date('2015-01-18'), y: 874.45 }
        ,{ x: new Date('2015-01-25'), y: 874.51 }
        ,{ x: new Date('2015-02-01'), y: 874.52 }
        ,{ x: new Date('2015-02-08'), y: 874.65 }
        ,{ x: new Date('2015-02-15'), y: 874.65 }
        ,{ x: new Date('2015-02-22'), y: 874.79 }
        ,{ x: new Date('2015-03-01'), y: 875.11 }
        ,{ x: new Date('2015-03-08'), y: 887.06 }
        ,{ x: new Date('2015-03-15'), y: 905.06 }
        ,{ x: new Date('2015-03-22'), y: 905.12 }
        ,{ x: new Date('2015-03-29'), y: 905.12 }
        ,{ x: new Date('2015-04-05'), y: 905.12 }
        ,{ x: new Date('2015-04-12'), y: 905.12 }
        ,{ x: new Date('2015-04-19'), y: 908.56 }
*/
      ]
    }
  ];
        new Chart(ctx2).Scatter( ChartData2,
      {
        showScale: true,
        scaleShowLabels: true,
        scaleShowHorizontalLines: true,
        scaleShowVerticalLines: true,
        scaleLineWidth: 1,
        scaleLineColor: "red",
        scaleGridLineColor: "#999",
        scaleLabel: "<%=value%> Mb",
        scaleArgLabel: "<%=value%>mmm",
        scaleGridLineWidth: 1,
        scaleType: "date",
        bezierCurve: false,
        animation: false,
        pointDot: true
      }
    );
    </script>
  <br>Script complete
</body>
</html>
```

**Comment by dima117** [comment]
Could you give an example on http://jsfiddle.net or similar site?

**Comment by AndyEm-BT** [comment]
Will try, but this is the first time I've used GitHub or anything like it.

Thanks for the speedy reply.

Andy

Sent from my Windows Phone

**Comment by dima117** [comment]
Fixed. See an example in "test.html" file.

**Comment by AndyEm-BT** [comment]
Wow. Which time zone are you in? I’m in the UK (+00:00) and mailed you just before I finished work. I started again early this morning to find your fix already in my inbox! I still need to learn http://jsfiddle.net though…

My test chart now looks like the image below, and is just what I wanted.
Even the display of the labels for multiple points (where the points are very close together) is good; I don’t want user to have to be extremely precise with their mouse to pick up data.

[cid:image002.png@01D07C18.9121DFC0]

Andrew Emmerson
Database Administrator | Tel: 0121  4983260 | Mob: 07968 616 377 | E: andrew.emmerson@bt.commailto:andrew.emmerson@bt.com

BT Expedite
We are BT’s Retail Specialists
www.btexpedite.comhttp://www.btexpedite.com/   Twitterhttps://twitter.com/BTExpedite   YouTubehttp://www.youtube.com/user/BTExpedite  LinkedInhttps://www.linkedin.com/company/bt-expedite   Pinteresthttp://uk.pinterest.com/btexpedite/

This email contains BT information, which may be privileged or confidential. It's meant only for the individual(s) or entity named above. If you're not the intended recipient, note that disclosing, copying, distributing or using this information is prohibited. If you've received this email in error, please let me know immediately on the email address above. Thank you. We monitor our email system, and may record your emails.

BT Expedite
Registered office: 81 Newgate Street, London EC1A 7AJ
Registered in England no: 1800000
BT Expedite is a trading identity of British Telecommunications plc

Think before you print. Please consider the environment before printing this email

**Comment by dima117** [comment]
I'm in Moscow, Russia (+03:00). Unfortunately I don't see your attached picture in github, but I hope that I helped you. Feel free to contact me if you will have any questions.

**Comment by AndyEm-BT** [comment]
It was my first time on GitHub – I still have a lot to learn.

Thanks
